name: _body_only
timestamp: 1559601011
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1500478101
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-5790: 'System Messages'
  content:
    system-content-7552: 'Page Content'
inherit: {  }
