name: _error
timestamp: 1555289537
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1502553408
positions: {  }
sections:
  header: Header
  navigation: Navigation
  sidebar: Sidebar
  mainbar: Mainbar
  abovefooter: Abovefooter
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-6091: 'System Messages'
  content:
    system-content-3910: 'Page Content'
  custom:
    custom-5592: 'Custom HTML'
    custom-2850: 'Custom HTML'
    custom-7118: 'About Us'
    custom-3704: Navigation
    custom-3615: Industry
    custom-4147: 'Header Contact'
  social:
    social-9438: Social
  logo:
    logo-9490: 'Logo / Image'
  menu:
    menu-7853: Menu
  branding:
    branding-9894: Branding
  mobile-menu:
    mobile-menu-1425: 'Mobile Menu'
inherit:
  default:
    header: header
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    custom-4147: custom-5173
    logo-9490: logo-1829
    menu-7853: menu-5263
    branding-9894: branding-4929
    mobile-menu-1425: mobile-menu-7330
