name: 9
timestamp: 1551046191
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: default
  timestamp: 1546799030
positions:
  slideshow: 'Module Position'
  subscribe: Subscribe
sections:
  header: Header
  navigation: Navigation
  slideshow: Slideshow
  sidebar: Sidebar
  mainbar: Mainbar
  abovefooter: Abovefooter
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-5173: 'Header Contact'
    custom-3704: Lions
    custom-7118: Pin
    custom-3615: Industry
  logo:
    logo-1754: 'Logo / Image'
  menu:
    menu-5263: Menu
    menu-1566: Menu
  position:
    position-position-1765: 'Module Position'
    position-position-4980: Subscribe
  messages:
    system-messages-4126: 'System Messages'
  content:
    system-content-1246: 'Page Content'
  social:
    social-9438: Social
  branding:
    branding-4929: Branding
  mobile-menu:
    mobile-menu-7330: 'Mobile Menu'
inherit:
  default:
    header: header
    navigation: navigation
    slideshow: slideshow
    sidebar: sidebar
    mainbar: mainbar
    aside: aside
    abovefooter: abovefooter
    footer: footer
    offcanvas: offcanvas
    custom-5173: custom-5173
    logo-1754: logo-1829
    menu-5263: menu-5263
    position-position-1765: position-position-1765
    system-messages-4126: system-messages-4126
    system-content-1246: system-content-1246
    custom-3704: custom-3704
    custom-7118: custom-7118
    custom-3615: custom-3615
    social-9438: social-9438
    position-position-4980: position-position-4980
    branding-4929: branding-4929
    mobile-menu-7330: mobile-menu-7330
